/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referring to this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-weixin': '&#xe600;',
		'icon-weibo': '&#xe601;',
		'icon-tencent-weibo': '&#xe602;',
		'icon-renren': '&#xe603;',
		'icon-qzone': '&#xe604;',
		'icon-qq': '&#xe605;',
		'icon-kaixin': '&#xe606;',
		'icon-uniF000': '&#xf000;',
		'icon-calendar': '&#xe000;',
		'icon-reorder': '&#xe001;',
		'icon-pen': '&#xe002;',
		'icon-edit': '&#xe003;',
		'icon-feed': '&#xe004;',
		'icon-feed-2': '&#xe005;',
		'icon-bubbles': '&#xe006;',
		'icon-comment': '&#xe007;',
		'icon-comments': '&#xe008;',
		'icon-user': '&#xe009;',
		'icon-user-add': '&#xe00a;',
		'icon-users': '&#xe00b;',
		'icon-home': '&#xe00c;',
		'icon-book': '&#xe00d;',
		'icon-book-2': '&#xe00e;',
		'icon-star': '&#xe00f;',
		'icon-star-half': '&#xe010;',
		'icon-star-empty': '&#xe011;',
		'icon-binoculars<br>': '&#xe012;',
		'icon-uniE013': '&#xe013;',
		'icon-envelope': '&#xe014;',
		'icon-phone': '&#xe015;',
		'icon-mobile': '&#xe016;',
		'icon-phone-2': '&#xe017;',
		'icon-address-book': '&#xe018;',
		'icon-map-pin-fill': '&#xe019;',
		'icon-map-pin-stroke': '&#xe01a;',
		'icon-uniE01B': '&#xe01b;',
		'icon-briefcase': '&#xe01c;',
		'icon-airplane': '&#xe01d;',
		'icon-glass': '&#xe01e;',
		'icon-mug': '&#xe01f;',
		'icon-camera': '&#xe020;',
		'icon-microphone': '&#xe021;',
		'icon-drink': '&#xe022;',
		'icon-checkmark': '&#xe023;',
		'icon-cancel': '&#xe024;',
		'icon-grid': '&#xe025;',
		'icon-list': '&#xe026;',
		'icon-cloudy': '&#xe027;',
		'icon-cloud': '&#xe028;',
		'icon-weather': '&#xe029;',
		'icon-weather-2': '&#xe02a;',
		'icon-weather-3': '&#xe02b;',
		'icon-lines': '&#xe02c;',
		'icon-cloud-2': '&#xe02d;',
		'icon-lightning': '&#xe02e;',
		'icon-rainy-2': '&#xe030;',
		'icon-windy': '&#xe031;',
		'icon-windy-2': '&#xe032;',
		'icon-snowy': '&#xe033;',
		'icon-snowy-2': '&#xe034;',
		'icon-snowy-3': '&#xe035;',
		'icon-weather-4': '&#xe036;',
		'icon-cloudy-2': '&#xe037;',
		'icon-cloud-3': '&#xe038;',
		'icon-lightning-2': '&#xe039;',
		'icon-sun': '&#xe03a;',
		'icon-moon': '&#xe03b;',
		'icon-sunrise': '&#xe049;',
		'icon-moon-2': '&#xe04a;',
		'icon-sun-2': '&#xe04b;',
		'icon-sun-3': '&#xe04c;',
		'icon-windy-5': '&#xe04d;',
		'icon-wind': '&#xe04e;',
		'icon-snowflake': '&#xe04f;',
		'icon-lightning-5': '&#xe050;',
		'icon-cog': '&#xe051;',
		'icon-rotate': '&#xe052;',
		'icon-logout': '&#xe053;',
		'icon-login': '&#xe054;',
		'icon-uniE055': '&#xe055;',
		'icon-heart': '&#xe056;',
		'icon-heart-2': '&#xe057;',
		'icon-thumbs-up<br>': '&#xe058;',
		'icon-thumbs-down<br>': '&#xe059;',
		'icon-mouse': '&#xe05a;',
		'icon-uniE05B': '&#xe05b;',
		'icon-earth': '&#xe05c;',
		'icon-uniE05D': '&#xe05d;',
		'icon-arrow-left': '&#xe05e;',
		'icon-arrow-down': '&#xe05f;',
		'icon-arrow-up': '&#xe060;',
		'icon-arrow-right': '&#xe061;',
		'icon-arrow-left-2': '&#xe062;',
		'icon-arrow-down-2': '&#xe063;',
		'icon-arrow-up-2': '&#xe064;',
		'icon-arrow-right-2': '&#xe065;',
		'icon-facebook': '&#xe066;',
		'icon-googleplus': '&#xe067;',
		'icon-twitter': '&#xe068;',
		'icon-linkedin': '&#xe069;',
		'icon-uniE06A': '&#xe06a;',
		'icon-trash': '&#xe06b;',
		'icon-step-backward': '&#xe06c;',
		'icon-fast-backward': '&#xe06d;',
		'icon-backward': '&#xe06e;',
		'icon-pay': '&#xe06f;',
		'icon-pause': '&#xe070;',
		'icon-stop': '&#xe071;',
		'icon-forward': '&#xe072;',
		'icon-fast-forward': '&#xe073;',
		'icon-step-forward': '&#xe074;',
		'icon-eject': '&#xe075;',
		'icon-badge': '&#xe076;',
		'icon-cup': '&#xe077;',
		'icon-uniE078': '&#xe078;',
		'icon-image': '&#xe079;',
		'icon-uniE07A': '&#xe07a;',
		'icon-Celcius': '&#xe07b;',
		'icon-Fahrenheit': '&#xe07c;',
		'icon-none': '&#xe07d;',
		'icon-thermometer': '&#xe07e;',
		'icon-compas': '&#xe07f;',
		'icon-fullscreen': '&#xe080;',
		'icon-fullscreen-exit': '&#xe081;',
		'icon-left-quote': '&#xe082;',
		'icon-right-quote': '&#xe083;',
		'icon-drink-2': '&#xe084;',
		'icon-coffee': '&#xe085;',
		'icon-ice-cream': '&#xe086;',
		'icon-mug-2': '&#xe087;',
		'icon-drink-3': '&#xe088;',
		'icon-painting': '&#xe089;',
		'icon-uniE08A': '&#xe08a;',
		'icon-tie': '&#xe08b;',
		'icon-heart-3': '&#xe08c;',
		'icon-heart-4': '&#xe08d;',
		'icon-plus': '&#xe08e;',
		'icon-library': '&#xe08f;',
		'icon-building': '&#xe090;',
		'icon-hospital': '&#xe091;',
		'icon-office-2': '&#xe092;',
		'icon-moon-3': '&#xe093;',
		'icon-earth-2': '&#xe094;',
		'icon-pig': '&#xe095;',
		'icon-paperclip': '&#xe096;',
		'icon-bag': '&#xe097;',
		'icon-baseball': '&#xe098;',
		'icon-graduate': '&#xe099;',
		'icon-suitcase': '&#xe09a;',
		'icon-direction': '&#xe09b;',
		'icon-ticket': '&#xe09c;',
		'icon-clipboard': '&#xe09d;',
		'icon-navigtaion': '&#xe09e;',
		'icon-uniE09F': '&#xe09f;',
		'icon-gradu': '&#xe0a0;',
		'icon-piano': '&#xe0a1;',
		'icon-music<br>': '&#xe0a2;',
		'icon-graduation<br>': '&#xe0a3;',
		'icon-heart-5': '&#xe0a4;',
		'icon-user-2': '&#xe0a5;',
		'icon-spinner': '&#xe0a6;',
		'icon-smiley': '&#xe0a7;',
		'icon-mail': '&#xe0a8;',
		'icon-envelope-alt': '&#xe0a9;',
		'icon-envelope-2': '&#xe0aa;',
		'icon-envelope-3': '&#xe0ab;',
		'icon-picture': '&#xe0ac;',
		'icon-pictures': '&#xe0ad;',
		'icon-cloud-6': '&#xe0ae;',
		'icon-flag': '&#xe0af;',
		'icon-edit-2': '&#xe0b0;',
		'icon-pencil': '&#xe0b1;',
		'icon-uniE02F': '&#xe02f;',
		'icon-baidu': '&#xe607;',
		'icon-reddit': '&#xe608;',
		'icon-share': '&#xe609;',
		'icon-search': '&#xe60a;',
		'icon-qrcode': '&#xe60b;',
		'icon-cart': '&#xe60c;',
		'icon-tags': '&#xe60d;',
		'icon-tag': '&#xe60e;',
		'icon-new-tab': '&#xe60f;',
		'icon-equalizer': '&#xe610;',
		'icon-chrome': '&#xe611;',
		'icon-food': '&#xe612;',
		'icon-bed': '&#xe613;',
		'icon-certificate': '&#xe614;',
		'icon-office': '&#xe615;',
		'icon-trophy': '&#xe616;',
		'icon-aid': '&#xe617;',
		'icon-warmedal': '&#xe618;',
		'icon-music': '&#xe619;',
		'icon-headphones': '&#xe61a;',
		'icon-beer': '&#xe61b;',
		'icon-bookmark': '&#xe61c;',
		'icon-uniF7CA': '&#xe61d;',
		'icon-captainamerica': '&#xe61e;',
		'icon-businesscard2': '&#xe61f;',
		'icon-woman': '&#xe620;',
		'icon-fantastico': '&#xe621;',
		'icon-qrcode2': '&#xe622;',
		'icon-settings3': '&#xe623;',
		'icon-settings5': '&#xe624;',
		'icon-lock': '&#xe625;',
		'icon-unlocked': '&#xe626;',
		'icon-road': '&#xe627;',
		'icon-shuffle': '&#xe628;',
		'icon-loop': '&#xe629;',
		'icon-loop2': '&#xe62a;',
		'icon-error2': '&#xe62b;',
		'icon-error': '&#xe62c;',
		'icon-info': '&#xe62d;',
		'icon-info2': '&#xe62e;',
		'icon-man': '&#xe62f;',
		'icon-binoculars': '&#xe630;',
		'icon-zoom-in': '&#xe631;',
		'icon-zoom-out': '&#xe632;',
		'icon-rainy': '&#xe645;',
		'icon-key': '&#xe633;',
		'icon-gauge': '&#xe634;',
		'icon-graduation': '&#xe635;',
		'icon-info3': '&#xe636;',
		'icon-question': '&#xe637;',
		'icon-warning': '&#xe638;',
		'icon-help': '&#xe639;',
		'icon-info4': '&#xe63a;',
		'icon-search2': '&#xe63b;',
		'icon-dashboard': '&#xe63c;',
		'icon-thumbs-up': '&#xe63d;',
		'icon-thumbs-down': '&#xe63e;',
		'icon-thumbs-up2': '&#xe63f;',
		'icon-thumbs-down2': '&#xe640;',
		'icon-signal': '&#xe641;',
		'icon-female': '&#xe642;',
		'icon-male': '&#xe643;',
		'icon-shop': '&#xe644;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
