/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span class="icon" style="font-family: \'icons\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-calendar' : '&#xe000;',
			'icon-reorder' : '&#xe001;',
			'icon-pen' : '&#xe002;',
			'icon-edit' : '&#xe003;',
			'icon-feed' : '&#xe004;',
			'icon-feed-2' : '&#xe005;',
			'icon-bubbles' : '&#xe006;',
			'icon-comment' : '&#xe007;',
			'icon-comments' : '&#xe008;',
			'icon-user' : '&#xe009;',
			'icon-user-add' : '&#xe00a;',
			'icon-users' : '&#xe00b;',
			'icon-home' : '&#xe00c;',
			'icon-book' : '&#xe00d;',
			'icon-book-2' : '&#xe00e;',
			'icon-star' : '&#xe00f;',
			'icon-star-half' : '&#xe010;',
			'icon-star-empty' : '&#xe011;',
			'icon-binoculars' : '&#xe012;',
			'icon-info' : '&#xe013;',
			'icon-envelope' : '&#xe014;',
			'icon-phone' : '&#xe015;',
			'icon-mobile' : '&#xe016;',
			'icon-phone-2' : '&#xe017;',
			'icon-address-book' : '&#xe018;',
			'icon-map-pin-fill' : '&#xe019;',
			'icon-map-pin-stroke' : '&#xe01a;',
			'icon-signal' : '&#xe01b;',
			'icon-briefcase' : '&#xe01c;',
			'icon-airplane' : '&#xe01d;',
			'icon-glass' : '&#xe01e;',
			'icon-mug' : '&#xe01f;',
			'icon-camera' : '&#xe020;',
			'icon-microphone' : '&#xe021;',
			'icon-drink' : '&#xe022;',
			'icon-checkmark' : '&#xe023;',
			'icon-cancel' : '&#xe024;',
			'icon-grid' : '&#xe025;',
			'icon-list' : '&#xe026;',
			'icon-cloudy' : '&#xe027;',
			'icon-cloud' : '&#xe028;',
			'icon-weather' : '&#xe029;',
			'icon-weather-2' : '&#xe02a;',
			'icon-weather-3' : '&#xe02b;',
			'icon-lines' : '&#xe02c;',
			'icon-cloud-2' : '&#xe02d;',
			'icon-lightning' : '&#xe02e;',
			'icon-rainy' : '&#xe02f;',
			'icon-rainy-2' : '&#xe030;',
			'icon-windy' : '&#xe031;',
			'icon-windy-2' : '&#xe032;',
			'icon-snowy' : '&#xe033;',
			'icon-snowy-2' : '&#xe034;',
			'icon-snowy-3' : '&#xe035;',
			'icon-weather-4' : '&#xe036;',
			'icon-cloudy-2' : '&#xe037;',
			'icon-cloud-3' : '&#xe038;',
			'icon-lightning-2' : '&#xe039;',
			'icon-sun' : '&#xe03a;',
			'icon-moon' : '&#xe03b;',
			'icon-cloudy-3' : '&#xe03c;',
			'icon-cloud-4' : '&#xe03d;',
			'icon-cloud-5' : '&#xe03e;',
			'icon-lightning-3' : '&#xe03f;',
			'icon-cloudy-4' : '&#xe040;',
			'icon-weather-5' : '&#xe041;',
			'icon-snowy-4' : '&#xe042;',
			'icon-snowy-5' : '&#xe043;',
			'icon-windy-3' : '&#xe044;',
			'icon-windy-4' : '&#xe045;',
			'icon-rainy-3' : '&#xe046;',
			'icon-rainy-4' : '&#xe047;',
			'icon-lightning-4' : '&#xe048;',
			'icon-sunrise' : '&#xe049;',
			'icon-moon-2' : '&#xe04a;',
			'icon-sun-2' : '&#xe04b;',
			'icon-sun-3' : '&#xe04c;',
			'icon-windy-5' : '&#xe04d;',
			'icon-wind' : '&#xe04e;',
			'icon-snowflake' : '&#xe04f;',
			'icon-lightning-5' : '&#xe050;',
			'icon-cog' : '&#xe051;',
			'icon-rotate' : '&#xe052;',
			'icon-logout' : '&#xe053;',
			'icon-login' : '&#xe054;',
			'icon-key' : '&#xe055;',
			'icon-heart' : '&#xe056;',
			'icon-heart-2' : '&#xe057;',
			'icon-thumbs-up' : '&#xe058;',
			'icon-thumbs-down' : '&#xe059;',
			'icon-mouse' : '&#xe05a;',
			'icon-search' : '&#xe05b;',
			'icon-earth' : '&#xe05c;',
			'icon-cart' : '&#xe05d;',
			'icon-arrow-left' : '&#xe05e;',
			'icon-arrow-down' : '&#xe05f;',
			'icon-arrow-up' : '&#xe060;',
			'icon-arrow-right' : '&#xe061;',
			'icon-arrow-left-2' : '&#xe062;',
			'icon-arrow-down-2' : '&#xe063;',
			'icon-arrow-up-2' : '&#xe064;',
			'icon-arrow-right-2' : '&#xe065;',
			'icon-facebook' : '&#xe066;',
			'icon-googleplus' : '&#xe067;',
			'icon-twitter' : '&#xe068;',
			'icon-linkedin' : '&#xe069;',
			'icon-sina-weibo' : '&#xe06a;',
			'icon-trash' : '&#xe06b;',
			'icon-step-backward' : '&#xe06c;',
			'icon-fast-backward' : '&#xe06d;',
			'icon-backward' : '&#xe06e;',
			'icon-play' : '&#xe06f;',
			'icon-pause' : '&#xe070;',
			'icon-stop' : '&#xe071;',
			'icon-forward' : '&#xe072;',
			'icon-fast-forward' : '&#xe073;',
			'icon-step-forward' : '&#xe074;',
			'icon-eject' : '&#xe075;',
			'icon-badge' : '&#xe076;',
			'icon-cup' : '&#xe077;',
			'icon-office' : '&#xe078;',
			'icon-image' : '&#xe079;',
			'icon-food' : '&#xe07a;',
			'icon-Celsius' : '&#xe07b;',
			'icon-Fahrenheit' : '&#xe07c;',
			'icon-none' : '&#xe07d;',
			'icon-thermometer' : '&#xe07e;',
			'icon-compass' : '&#xe07f;',
			'icon-fullscreen' : '&#xe080;',
			'icon-fullscreen-exit' : '&#xe081;',
			'icon-left-quote' : '&#xe082;',
			'icon-right-quote' : '&#xe083;',
			'icon-drink-2' : '&#xe084;',
			'icon-coffee' : '&#xe085;',
			'icon-ice-cream' : '&#xe086;',
			'icon-mug-2' : '&#xe087;',
			'icon-drink-3' : '&#xe088;',
			'icon-painting' : '&#xe089;',
			'icon-aid' : '&#xe08a;',
			'icon-tie' : '&#xe08b;',
			'icon-heart-3' : '&#xe08c;',
			'icon-heart-4' : '&#xe08d;',
			'icon-plus' : '&#xe08e;',
			'icon-library' : '&#xe08f;',
			'icon-building' : '&#xe090;',
			'icon-hospital' : '&#xe091;',
			'icon-office-2' : '&#xe092;',
			'icon-moon-3' : '&#xe093;',
			'icon-earth-2' : '&#xe094;',
			'icon-pig' : '&#xe095;',
			'icon-paperclip' : '&#xe096;',
			'icon-bag' : '&#xe097;',
			'icon-baseball' : '&#xe098;',
			'icon-graduate' : '&#xe099;',
			'icon-suitcase' : '&#xe09a;',
			'icon-direction' : '&#xe09b;',
			'icon-ticket' : '&#xe09c;',
			'icon-clipboard' : '&#xe09d;',
			'icon-navigation' : '&#xe09e;',
			'icon-warning' : '&#xe09f;',
			'icon-help' : '&#xe0a0;',
			'icon-piano' : '&#xe0a1;',
			'icon-music' : '&#xe0a2;',
			'icon-graduation' : '&#xe0a3;',
			'icon-heart-5' : '&#xe0a4;',
			'icon-user-2' : '&#xe0a5;',
			'icon-spinner' : '&#xe0a6;',
			'icon-smiley' : '&#xe0a7;',
			'icon-mail' : '&#xe0a8;',
			'icon-envelope-alt' : '&#xe0a9;',
			'icon-envelope-2' : '&#xe0aa;',
			'icon-envelope-3' : '&#xe0ab;',
			'icon-picture' : '&#xe0ac;',
			'icon-pictures' : '&#xe0ad;',
			'icon-cloud-6' : '&#xe0ae;',
			'icon-flag' : '&#xe0af;',
			'icon-edit-2' : '&#xe0b0;',
			'icon-pencil' : '&#xe0b1;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};